
[functions.create-chatbot-settings]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.chatbot-response]
verify_jwt = false

[functions.create-enterprise-user]
verify_jwt = true

[functions.get-system-logs]
verify_jwt = true

[functions.get-user-usage-stats]
verify_jwt = true

[functions.import-properties]
verify_jwt = true

[functions.lead-qualification]
verify_jwt = true

[functions.match-leads-to-listings]
verify_jwt = true

[functions.process-whatsapp-message]
verify_jwt = true

[functions.web-scraper]
verify_jwt = true

[functions.process-pdf-content]
verify_jwt = false

[functions.web-crawler]
verify_jwt = false

[functions.search-training-data]
verify_jwt = false

[functions.search-properties]
verify_jwt = false

[functions.search-property-listings]
verify_jwt = false

[functions.get-conversation-history]
verify_jwt = false

[functions.analyze-intent]
verify_jwt = false
